# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_api', '0002_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
