# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_api', '0003_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(help_text='s=second, m=minute, h=hour, d=day. ex: 5m=5 minutes', max_length=200),
        ),
    ]
