# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_api', '0004_auto_20170503_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
